import struct

CODING_FORMAT = "utf-8"

# REWRITE
ACK = b"OK"
NACK = b"ERROR"
KEEP_ALIVE = b"KA"
ENDING = b"END."


STARTING_HEADER_WO_CHECKSUM = "IHc" # Fragments amount + Fragment size + Data Type
STARTING_HEADER = "IHHc" # Fragments amount + Fragment size + Checksum + Data Type

FRAGMENT_INDEX = "I"
CHECKSUM = "H"
DATA_HEADER = FRAGMENT_INDEX + CHECKSUM

STARTING_HEADER_SIZE = struct.calcsize(STARTING_HEADER) # bytes
DATA_HEADER_SIZE = struct.calcsize(DATA_HEADER)

MAX_STARTING_HEADER_SIZE = 255 + STARTING_HEADER_SIZE
# TODO : delete
SEGMENTS_AMOUNT = 10
MAXIMUM_THREADS = 5

# NOT SURE WHY IS IT HERE 
MAX_FILE_NAME_SIZE = 255
MIN_FRAGMENT_SIZE = 50
MAX_FRAGMENT_SIZE = 1466