CODING_FORMAT = "utf-8"
ACK = b"OK"
NACK = b"ERROR"
KEEP_ALIVE = b"KA"
ENDING = b"END."
STARTING_HEADER = "ihhc" # Fragments amount + Fragment size + Checksum + Data Type
DATA_HEADER = "ih"
SEGMENTS_AMOUNT = 10 # how many segments will be sent at once
MAXIMUM_THREADS = 5
STARTING_HEADER_SIZE = 9 # bytes
DATA_HEADER_SIZE = 6 # bytes